sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: nTtDJ7BvW5kPsGvlojjVIBdZeTJCJmoS7LYhlw4INN4zDf7T4O5zkwXF5V2lIrqEgGe2wULGjkPP81Ip0cx7fINMDrivZRl0ocF823kblzse0IxmUOkSTRPQB4xuzkLfSTzAnTn4myb/JXGa7qYaCC6XnmCMuG4mTRyEgkXxd6XunfeB1ZWf5pPycLyYHm/IzLz6OM5GsJvXM/3B641hTs3EHOW/R0hv7nSI7NlHmW0WfvEPunhZhKNTgzTWKbvSLuoO9wx65jcUIaxYsiQ269iq/yDSpMpHBhAyfekvJ3aX9uFX3p7Evn68P1PAuJL85TsiEIDi0ZdBD9J6iElsvemLvGMWI119P9gO+FH4nFUd5Y9sflDTjluCuNgqWpjY1qYEY2KQCh6ZiaR19vfYhlX7gqdTr/wLypHNLup/PsheosqzfKTcDDPJXSMmKS/RavDKWbtotssk4ns38OHyVJn0tK74AhFlzMaAPW86HElRhmkyjcl+OGLG4wokz6aigNXyUZF9Zaqco8chhQpfwPlzHygcDHqSQCcb3tJgBLatKnOif0ASL5yqitersxBYBZQ84D634ZvJQ4Tnn3gwbTOAtbGlqM1M5zwEw7ZWBmclzixSGP88UPKqopgcYXUAP35J4EMZMPsukx/msLM5ziySHVSrcIJjU4TnWzWLutU=
