version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      nqbuPxdA56EH/aJBalKBxOFVYBpZuJZvxv/bdIXFTy1pcsNRuFWR7p1yVj8PMFNJsUtrN782oVF30YtXgAZ+I4fTY2KOBVBqJ+vjaJMTftSTGVGay/ZB3IeGB5AKXqTd2HdeJArzyRm7Dhkj59FSmG/lhcyBa/F13K9iXPO/Vgft/6YknO20eML0t8gSZwY8+Kc6nc9Ce4XGYTsH7BNByKzFD9nGY7jxJuvuRZ5uJv3ADYLNdBlVYbJ1+E8GuKbpF8GXCOJnUTozHoKbilcIRd/vxShEJ4bpHRnh2+F5xGQnYZzONa3DX5o+k00ejDzQXjJqeMk15gN0BNJZOnD9YwxIPxy+9AocifewoBcrspo04k2ZxY0G9XUHHR813OYAPSzB/48wBxTQ0ktApJR/iMc6ouFn5HVGRdBy/WHeJNjGmBniD29AkLbVYPuojVCANQy0ldW7sbtUR7WqAwKbeWi4Vq1+j3BXtxl2ry15VmZQ11rxwGe6lSxhHbIEZlH9RAesCud2Nsd5nM4f20cOE1axQt4ljJRTBG7ms5GSaiZoZMKmJ2Mnlj70cUyjSc9JMMqioyNOgumWctLLoQJ1TL8EBA3e4rBvIC1tFCKzA3ymfAGXSccdj59n5TiHXlqrgLnNsfPbJCeeqfLoRgTocXo6dU5AQu9RCSu+hjBJiFM=
