version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      MTd4gHThrdovFVwClRlXe2Jf1PF027kxeGYBWo11xyD2SlExKr7VCHfeo87hhNcZxRl1mULnIek8pF5ei9QBqQhZlkMY4kT1pnY+p61G1N0PCuz60dAwB8lhAP/ZQqncM3AChq1vZLN1CGGcGQkt8HFjPiUA0qfRWbIuRSRqP1we5GN6U2UoY8IWpa7zxi1QpWkihQHtyYEMPrc5iNofKg1k5kmZlpapXczXPfC1laYeU6KrtDCElcdT4+bvKck5N7sGpgKrDm5D2rVxbOnzKiKZBHbBw4Rd+KMF3YNhi57cbMBr5QC2Lfo9hhFlJ3JyV6LXgnPdksbxown2t8TceLiqaw0LjTAVhh6zb/gVzdnkcxT2RgH/PYvQS0hmojW/dEjFSG1AM/dBGZCAE2NA2GRc21idrZ3ipESUx22KFH83XRKsfxOcK2/hFWWRkOqAGX/0VHaIx8iVgbLJBFaj0ioF16DRe7shYqsITSHByLlGh0JOS+X3sqEkNHXHpqr9OA3ToqL+0AY7ta6I/hGI1IQWgsC5BOiOittSzxBGF8uBHAOH/N2mhM7r1//H8ESlpzABKfXr1w8TELsuJNohFnA1GX5eVGO5aTEHDsxtCSx4F2fowVToqio2g3sStBWntblwXPnqe6ZrCzPZB21XYbcc9T47DVapA0+i4FA2BLg=
